"""
Django settings for steam project.

Generated by "django-admin startproject" using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from environ import Env
from datetime import timedelta

env = Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent

env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don"t run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "users",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "steam.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "steam.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    # The db() method is an alias for db_url().
    "default": env.db(),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

BACKEND_URL = env("BACKEND_URL")
FRONTEND_URL = env("FRONTEND_URL")

CORS_ALLOWED_ORIGINS = [FRONTEND_URL]  # Allowed path

# CORS SETTINGS (cookie access)
CORS_ALLOW_CREDENTIALS = True  # allow send cookies

# JWT SETTINGS
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,      # refresh token
    "BLACKLIST_AFTER_ROTATION": True,   # blacklist old token
    "AUTH_COOKIE": "refresh_token",     # cookie name
    "AUTH_COOKIE_HTTP_ONLY": True,      # block js access
    "AUTH_COOKIE_PATH": "/",            # Allowed path (all site)
    "AUTH_COOKIE_SAMESITE": "Lax",      # CSRF Protection
    "AUTH_COOKIE_SECURE": False,        # True in production (HTTPS)
}

# SESSION SETTINGS
SESSION_COOKIE_SECURE = False      # True in production (HTTPS)
SESSION_COOKIE_HTTPONLY = True     # block js access
SESSION_COOKIE_SAMESITE = "Lax"    # CSRF Protection

# CSRF SETTINGS
CSRF_COOKIE_SECURE = False            # True in production (HTTPS)
CSRF_COOKIE_SAMESITE = "Lax"          # CSRF Protection
CSRF_TRUSTED_ORIGINS = [FRONTEND_URL]  # Allowed path

# REST FRAMEWORK SETTINGS (JWT AUTHENTICATION)
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",  # JWT Authentication
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",     # Authorization
    ),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",     # Anonymous throttling
        "rest_framework.throttling.UserRateThrottle"      # User throttling
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",          # Anonymous limiter
        "user": "1000/hour",        # User limiter
        "resend_email": "3/hour",   # Resend email limiter
        "login": "5/minute"         # Login limiter
    }
}

AUTH_USER_MODEL = "users.CustomUser"  # CustomUser

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # Send email to console

EMAIL_HOST_USER = env("EMAIL_HOST_USER")  # Email host user

SALT_ACTIVATION_ACCOUNT = env("SALT_ACTIVATION_ACCOUNT")  # activate-token

SALT_RESET_PASSWORD = env("SALT_RESET_PASSWORD")  # reset-token

TOKEN_MAX_AGE = timedelta(hours=1)  # token max age
